config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :edit, :destroy] do
    resources :pantries, only: [:new, :create, :show, :edit, :destroy]
  end
  resources :recipes, only: [:new, :create, :show, :edit, :destroy]
  resources :ingredients, only: [:new, :create]
  resources :available_ingredients, only: [:create]
  resources :required_ingredients, only: [:create]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_ingredient.rb
class AvailableIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :pantry
  validates :quantity, :ingredient_id, :pantry_id, presence: true
  validates :ingredient_id, uniqueness: {scope: :pantry_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :required_ingredients
  has_many :available_ingredients
  has_many :pantries, through: :available_ingredients
  has_many :recipes, through: :required_ingredients
  validates :name, uniqueness: {scope: :wet}

  def self.sorted_ingredients
    Ingredient.all.order(:name)
  end
end

app/models/pantry.rb
class Pantry < ApplicationRecord
  belongs_to :user
  has_many :available_ingredients
  has_many :ingredients, through: :available_ingredients
  validates :location, presence: true
  validates :location, uniqueness: {scope: :user_id}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :required_ingredients
  has_many :ingredients, through: :required_ingredients
  validates :name, :instructions, presence: true
  validates :name, uniqueness: true
end

app/models/required_ingredient.rb
class RequiredIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  validates :recipe_id, :ingredient_id, :quantity, :unit, presence: true
  validates :ingredient_id, uniqueness: {scope: :recipe_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true
  has_many :pantries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :require_login

  def current_user
    if session[:user_id].present?
      user = User.find_by(id: session[:user_id])
    end
  end

  def require_login
    unless current_user
      redirect_to root_url
    end
  end

end

app/controllers/available_ingredients_controller.rb
class AvailableIngredientsController < ApplicationController
  before_action :require_login

  def create
    @ingredients = Ingredient.all
    @available = AvailableIngredient.new(available_params)
    if @available.save
      redirect_to user_pantry_path(current_user, params[:available_ingredient][:pantry_id])
    else
      render :'/pantries/edit'
    end
  end

  private
    def available_params
      params.require(:available_ingredient).permit(:ingredient_id, :pantry_id, :quantity, :unit)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_login
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :wet)
    end
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController
  before_action :require_login
  def new
    @pantry = Pantry.new
  end

  def edit
    @pantry = Pantry.find_by(id: params[:id])
    @ingredients = Ingredient.sorted_ingredients
    @available = @pantry.available_ingredients.build
  end

  def create
    @pantry = Pantry.new(pantry_params)
    @pantry.user_id = current_user.id
    if @pantry.save
      redirect_to user_pantry_path(current_user, @pantry)
    else
      render :new
    end
  end

  def show
    @pantry = Pantry.find_by(id: params[:id])
  end

  private

    def pantry_params
      params.require(:pantry).permit(:location)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login
  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
    @ingredients = Ingredient.all.order(:name)
    @required = @recipe.required_ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :instructions)
    end
end

app/controllers/required_ingredients_controller.rb
class RequiredIngredientsController < ApplicationController
  before_action :require_login

  def create
    @ingredients = Ingredient.all
    @required = RequiredIngredient.new(available_params)
    if @required.save
      redirect_to recipe_path(params[:required_ingredient][:recipe_id])
    else
      render :'/recipes/edit'
    end
  end

  private
    def available_params
      params.require(:required_ingredient).permit(:ingredient_id, :recipe_id, :quantity, :unit)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      if user = User.find_by(email: auth_hash["info"]["email"])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        user = User.new(email: auth_hash['info']['email'], password: SecureRandom.hex, name: auth_hash['info']['name'])
        if user.save
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
          raise users.errors.full_messages.inspect
        end
      end
    else
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        render :new
      end
    end
  end

  def destroy
    if current_user
      session.delete :user_id
      redirect_to root_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    if params[:user][:password] == params[:user][:password_confirmation]
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        render :new
      end
    end
  end

  def show
    @user = User.find_by(id: session[:user_id])
    if @user.pantries.empty?
      redirect_to new_user_pantry_path(@user)
    end
    @pantries = @user.pantries
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/new.html.erb
<%if @ingredient.errors.any?%>
  <div class='fields_with_errors'>
    <%@ingredient.errors.full_messages.each do |msg|%>
      <%=msg%>
    <%end%>
  </div>
<%end%>
<%=form_for(@ingredient) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.label :wet%>
  <%=f.check_box :wet%>
  <%=f.submit%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pantry Pal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='nav-bar'>
      <%if !current_user%>
        <%=link_to "Sign Up", new_user_path%>
        <%=link_to "Sign In", signin_path%>
      <%else%>
        <%=link_to "Sign Out", logout_path, method: 'delete'%>
      <%end%>
      <%=link_to "Home", root_url%>
      <%if current_user%>
        <%=link_to "Your Pantries", user_path(current_user)%>
      <%end%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pantries/edit.html.erb
<%if @available.errors.any?%>
  <div class='fields_with_errors'>
    <%@available.errors.full_messages.each do |msg|%>
      <%=msg%>
    <%end%>
  </div>
<%end%>
<p>Please update the quantites you have on hand.</p>
<%=form_for(@available) do |f|%>
  <%=f.collection_select(:ingredient_id, @ingredients, :id, :name)%>
  <%=hidden_field_tag :"available_ingredient[pantry_id]", params[:id]%>
  <%=text_field_tag :"available_ingredient[quantity]"%>
  <%=select_tag :"available_ingredient[unit]", raw("<option>Fluid Oz</option>
                             <option>Cup</option>
                             <option>Pint</option>
                             <option>Quart</option>
                             <option>Gallon</option>
                             <option>Other</option>
                             <option>Teaspoon</option>
                             <option>Tablespoon</option>")%>
  <%=submit_tag%>
<br>
<%end%>
<br>
<%=link_to "Add Ingredient", new_ingredient_path%>

app/views/pantries/new.html.erb
<%if @pantry.errors.any?%>
  <div class='fields_with_errors'>
  <%@pantry.errors.full_messages.each do |msg|%>
    <%=msg%>
  <%end%>
  </div>
<%end%>
<%=form_for @pantry, url: user_pantries_path do |f|%>
  <%=f.label :location%>
  <%=f.text_field :location%>
  <%=f.submit%>
<%end%>

app/views/pantries/show.html.erb
<h1><%=@pantry.location%></h1>
<table>
  <tr>
    <th>Item</th>
    <th>Quantity</th>
    <th>Unit</th>
  </tr>
<%@pantry.available_ingredients.each do |ing|%>
    <tr>
      <td><%=Ingredient.find(ing.ingredient_id).name%></td>
      <td><%=ing.quantity%></td>
      <td><%=ing.unit%></td>
    </tr>
  <%end%>
</table>
<%=link_to "Edit Pantry", edit_user_pantry_path(current_user, @pantry)%>
<br>
<%=link_to "Add Recipe", new_recipe_path%><br><br>
<%Recipe.all.each do |rec|%>
  <%=link_to rec.name, recipe_path(rec)%><br>
<%end%>

app/views/recipes/edit.html.erb
<%if @required.errors.any?%>
  <div class='fields_with_errors'>
    <%@required.errors.full_messages.each do |msg|%>
      <%=msg%>
    <%end%>
  </div>
<%end%>
<p>Please update the quantites required for this recipe.</p>
<%=form_for(@required) do |f|%>
  <%=f.collection_select(:ingredient_id, @ingredients, :id, :name)%>
  <%=hidden_field_tag :"required_ingredient[recipe_id]", params[:id]%>
  <%=text_field_tag :"required_ingredient[quantity]"%>
  <%=select_tag :"required_ingredient[unit]", raw("<option>Fluid Oz</option>
                             <option>Cup</option>
                             <option>Pint</option>
                             <option>Quart</option>
                             <option>Gallon</option>
                             <option>Other</option>
                             <option>Teaspoon</option>
                             <option>Tablespoon</option>")%>
  <%=submit_tag%>
<br>
<%end%>
<br>
<%=link_to "Add Ingredient", new_ingredient_path%>

app/views/recipes/new.html.erb
<%if @recipe.errors.any?%>
  <div class='fields_with_errors'>
    <%@recipe.errors.full_messages.each do |msg|%>
      <%=msg%>
    <%end%>
  </div>
<%end%>
<%=form_for(@recipe) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <br>

  <%=f.label :instructions%>
  <%=f.text_area :instructions%>
  <br>

  <%=f.submit%>
<%end%>

app/views/recipes/show.html.erb
<h1><%=@recipe.name%></h1>
<table>
  <th>
    <td>Item</td>
    <td>Quantity</td>
    <td>Unit</td>
  </th>
<%@recipe.required_ingredients.each do |ing|%>
    <tr>
      <td><%=Ingredient.find(ing.ingredient_id).name%></td>
      <td><%=ing.quantity%></td>
      <td><%=ing.unit%></td>
    </tr>
  <%end%>
</table>
<p><%=@recipe.instructions%></p><br>
<%=link_to "Edit Recipe", edit_recipe_path(@recipe)%>
<br>

app/views/static_pages/home.html.erb
<h2>Welcome to Pantry Pal</h2>

app/views/users/new.html.erb
<%if @user.errors.any?%>
  <div class="fields_with_errors">
    <%@user.errors.full_messages.each do |msg|%>
      <%=msg%>
    <%end%>
  </div>
<%end%>
<%=form_for(@user) do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%>
  <%=f.label :email%>
  <%=f.text_field :email%>
  <%=f.label :password%>
  <%=f.password_field :password%>
  <%=f.label :password_confirmation%>
  <%=f.password_field :password_confirmation%>
  <%=f.submit%>
<%end%>

<a href="/auth/github">Sign In with Github!</a>

app/views/users/show.html.erb
<p>Which Pantry would you like to see?</p>
<%@pantries.each do |pantry|%>
  <%=link_to pantry.location, user_pantry_path(current_user, pantry)%><br>
<%end%>
<%=link_to "Add A Pantry", new_user_pantry_path(current_user)%>